services:
    App\Tests\MockClientCallback:
        public: true
        arguments:
            $paramPlanetePhpApiPrefix: '%afup.planete-php-api.base_uri%'

    App\Service\PlaneteService: '@App\Service\ApiPlaneteService'
